# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17

instance_class: F2


handlers:
- url: /images
  static_dir: static/images
  http_headers:
    Access-Control-Allow-Origin: *
  # ...


# [START appengine_websockets_yaml]
env: flex

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.
#manual_scaling:
 # instances: 1

network:
  session_affinity: true
# [END appengine_websockets_yaml]